#!/bin/bash
set -e

title="${1:-Qubes}"
text="${2:-Select qube:}"

qubes="$(python3 -c """
import sys
import qubesadmin
app = qubesadmin.Qubes()
qubes = [qube for qube in app.domains if qube.klass in ('AppVM', 'StandaloneVM') and not getattr(qube, 'template_for_dispvms', False) and qube.is_running() or ('servicevm' in qube.features and qube.is_running())]
for qube in sorted(qubes, key=lambda x: x.name):
    print(f'{qube.icon} {qube.name}')
""")"
# Sélection de la VM
SELECTED_VM=$(yad --list --on-top --no-headers --width 150 --height 300 --title "$title" --text "$text" --column ':IMG' --column '' $qubes)

# Traitement de la VM sélectionnée
SELECTED_VM=${SELECTED_VM#|} # supprimer le caractère de début de chaîne
SELECTED_VM=${SELECTED_VM%%|} # supprimer le caractère de fin de chaîne
echo "VM sélectionnée : $SELECTED_VM"

# Vérifier si une VM a été sélectionée
                if [ -z "$SELECTED_VM" ]; then
                echo "Aucune VM sélectionnée"
                exit 1
        fi

# Nouvelle fenêtre Yad avec les actions à effectuer sur la vm
SELECTED_ACTION=$(yad --title "Actions sur la vm $SELECTED_VM" --list --column  "Actions" "Arreter" "Démarrer/Redémarrer" "Tuer" "Lancer un terminal" "Lancer thunar"  --height=250)

# Supprimer le caractere de fin de saisie de chaine
SELECTED_ACTION=${SELECTED_ACTION%%|}

# Vérifier la valeur de SELECTED_ACTION
echo "Action sélectionnée : $SELECTED_ACTION"

# Execution de l'action sélectionnée sur la VM
case $SELECTED_ACTION in
        "Arreter")
        echo "Tentative d'arrêt de la VM $SELECTED_VM"
        qvm-shutdown "$SELECTED_VM"
                echo "La VM $SELECTED_VM a été arrêtée avec succès."
        ;;
        "Démarrer/Redémarrer")
        echo "Tentative de redémarrage de la VM $SELECTED_VM"
        qvm-shutdown "$SELECTED_VM"
                sleep 2
        qvm-start "$SELECTED_VM"
        echo "La VM $SELECTED_VM a été redémarrée."
	;;
	"Tuer")
	echo "Tentative pour tuer la VM $SELECTED_VM"
	qvm-kill "$SELECTED_VM"
		echo "La VM $SELECTED_VM a été tuée avec succés."
	;;
	"Lancer un terminal")
	echo "lancement du terminal"
	qvm-run --pass-io "$SELECTED_VM" xfce4-terminal
	;;
	"Lancer thunar")
	echo "Lancement de thunar"
	qvm-run --pass-io "$SELECTED_VM" thunar
	;;
esac
