#!/bin/bash

# Sélectionner le fichier source dans dom0
SRC_FILE=$(yad --file --title="Sélectionner le fichier à copier")
if [ $? -eq 0 ]; then

qubes="$(python3 -c """
import sys
import qubesadmin
app = qubesadmin.Qubes()
qubes = [qube for qube in app.domains if qube.klass in ('AppVM', 'StandaloneVM') and not getattr(qube, 'template_for_dispvms', False) and qube.is_running() or ('servicevm' in qube.features and qube.is_running())]
for qube in sorted(qubes, key=lambda x: x.name):
    print(f'{qube.icon} {qube.name}')
""")"
else
        echo "Opération annulée"
	yad --title="Opération annulée" --text="Opération annulée" --button="Ok"

        exit 1
fi

# Définir les variables title et text
title="Sélectionner un VM"
text="Veuillez choisir une machine virtuelle."

# Sélection de la VM
if
SELECTED_VM=$(yad --list --on-top --no-headers --width 150 --height 300 --title "$title" --text "$text" --column ':IMG' --column '' $qubes); then

# Traitement de la VM sélectionnée
SELECTED_VM=${SELECTED_VM#|} # supprimer le caractère de début de chaîne
SELECTED_VM=${SELECTED_VM%%|} # supprimer le caractère de fin de chaîne
echo "VM sélectionnée : $SELECTED_VM"
        else
        echo "Opération annulée"
	yad --title="Opération annulée" --text="Opération annulée" --button="Ok"
        exit 1
fi

# Afficher la fenêtre YAD pour sélectionner la machine virtuelle de destination
    DEST_VM=${SELECTED_VM%%|}
    DEST_FILE="/path/to/file_name_in_appvm"

 # Exécuter la commande de copie
        qvm-copy-to-vm "$DEST_VM" "$SRC_FILE"

# Vérifier si la commande de copie a réussi
if [ $? -eq 0 ]; then
        # Afficher une fenêtre Yad pour informer que le transfert est terminé
        yad --title "Transfert réussi" --text "Le fichier a été transféré avec succés vers $DEST_VM." --button="OK"
        else
        # Gérer l'erreur de copie si nécessaire
        yad --title "erreur" --text "Le transfert a échoué." --button="ok"
fi
